# Build the openai-reference binary
FROM golang:1.25 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.sum ./
# cache deps before building and copying source so that we don't need to re-download as much
RUN go mod download

# Copy the Go source
COPY cmd/ cmd/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o bin/openai-reference ./cmd/openai-reference

# Use distroless as minimal base image to package the openai-reference binary
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/bin/openai-reference .
USER 65532:65532

ENTRYPOINT ["/openai-reference"]
