# Image URL to use all building/pushing image targets
IMG ?= controller:latest
ROUTER_IMG ?= model-router:latest

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

.PHONY: all
all: build

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: manifests
manifests: controller-gen ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	"$(CONTROLLER_GEN)" rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
	cp config/crd/bases/*.yaml charts/agent-orca/crds/

.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	"$(CONTROLLER_GEN)" object:headerFile="hack/boilerplate.go.txt" paths="./..."

##@ API

.PHONY: openapi
openapi: ## Publish the OpenAPI specs (external task API + ACP API) to ./openapi/.
	@mkdir -p openapi
	@cp internal/apiserver/schemas/openapi-external.yaml openapi/external.yaml
	@cp internal/apiserver/schemas/openapi-acp.yaml openapi/acp.yaml
	@echo "OpenAPI specs written to openapi/external.yaml and openapi/acp.yaml"
	@echo "Live, embedded specs are served at:"
	@echo "  GET http://localhost:8084/openapi.json   (External Task API)"
	@echo "  GET http://localhost:8000/openapi.json   (ACP API)"

.PHONY: openapi-validate
openapi-validate: ## Validate the OpenAPI specs (requires redocly or swagger-cli).
	@if command -v redocly >/dev/null 2>&1; then \
		redocly lint internal/apiserver/schemas/openapi-external.yaml internal/apiserver/schemas/openapi-acp.yaml; \
	elif command -v swagger-cli >/dev/null 2>&1; then \
		swagger-cli validate internal/apiserver/schemas/openapi-external.yaml; \
		swagger-cli validate internal/apiserver/schemas/openapi-acp.yaml; \
	else \
		echo "install redocly or swagger-cli to validate" >&2; exit 1; \
	fi

##@ SDK / CLI

.PHONY: aoctl
aoctl: ## Build the aoctl CLI (bin/aoctl).
	go build -o bin/aoctl ./cmd/aoctl
	@echo "Built bin/aoctl — run './bin/aoctl --help' to get started."

.PHONY: sdk-python-smoke
sdk-python-smoke: ## Smoke-test the Python SDK against local stub servers.
	cd pkg/python/agentorca && python3 -m unittest discover -s tests

.PHONY: agent-sdk
agent-sdk: ## Build and publish the Python agent SDK (pkg/agentorca/).
	@echo "Building Python SDK package..."
	cd pkg/python/agentorca && python3 -m build --wheel 2>/dev/null || pip3 wheel . -w dist/
	@echo "SDK package built in pkg/python/agentorca/dist/"
	@echo "To install locally: pip3 install pkg/python/agentorca/dist/*.whl"
	@echo "To publish: twine upload pkg/python/agentorca/dist/*"

.PHONY: egress
egress: ## Build and run the egress package tests.
	go test -v ./internal/egress/... -coverprofile cover-egress.out
	@go tool cover -func cover-egress.out | tail -1


# cmd/ui-proxy/main.go uses `//go:embed dist`. The dist directory is gitignored
# (it is generated by `make build-ui-proxy` or inside the Dockerfile from the
# real React SPA). `go:embed` requires at least one non-hidden file in the
# directory (it ignores dotfiles and an empty directory is not embeddable), so
# we create a minimal placeholder here for tools that type-check the package
# (`go vet`, `golangci-lint`, `go test`) without needing the full SPA build.
.PHONY: ui-proxy-dist
ui-proxy-dist:
	@mkdir -p cmd/ui-proxy/dist
	@test -f cmd/ui-proxy/dist/index.html || \
		printf '<!-- stub for go:embed (gitignored) -->\n' > cmd/ui-proxy/dist/index.html

.PHONY: fmt
fmt: ui-proxy-dist ## Run go fmt against code.
	go fmt ./...

.PHONY: vet
vet: ui-proxy-dist ## Run go vet against code.
	go vet ./...

# Module-wide coverage: include all packages when any test runs (cross-package attribution).
# Per-package lines still show 0%% for packages that have no *_test.go; see total line after tests.
# Disable with: make test COVERPKG=
COVERPKG ?= $(shell go list -m)/...

.PHONY: test
test: manifests generate fmt vet setup-envtest ## Run tests.
	KUBEBUILDER_ASSETS="$(shell "$(ENVTEST)" use $(ENVTEST_K8S_VERSION) --bin-dir "$(LOCALBIN)" -p path)" \
		go test $(if $(COVERPKG),-coverpkg=$(COVERPKG)) $$(go list ./... | grep -v /e2e) -coverprofile cover.out
	@echo ""
	@echo "Total coverage (merged profile):"
	@go tool cover -func cover.out | tail -1

# TODO(user): To use a different vendor for e2e tests, modify the setup under 'tests/e2e'.
# The default setup assumes Kind is pre-installed and builds/loads the Manager Docker image locally.
# CertManager is installed by default; skip with:
# - CERT_MANAGER_INSTALL_SKIP=true
KIND_CLUSTER ?= agent-orca-test-e2e

# test-e2e: unified suite — creates a Kind cluster, deploys the operator, and runs all tests.
#
# Test tiers (controlled by env vars):
#   default             operator + webhook + split-pod resource creation tests
#   STREAMING_E2E=true  + SSE token streaming (needs LLM credentials)
#
# Examples:
#   make test-e2e
#   STREAMING_E2E=true make test-e2e
.PHONY: setup-test-e2e
setup-test-e2e: ## Set up a fresh Kind cluster for e2e tests (deletes existing cluster if present)
	@command -v $(KIND) >/dev/null 2>&1 || { \
		echo "Kind is not installed. Please install Kind manually."; \
		exit 1; \
	}
	@case "$$($(KIND) get clusters)" in \
		*"$(KIND_CLUSTER)"*) \
			echo "Deleting existing Kind cluster '$(KIND_CLUSTER)'..."; \
			$(KIND) delete cluster --name $(KIND_CLUSTER) ;; \
	esac
	@echo "Creating Kind cluster '$(KIND_CLUSTER)'..."
	@$(KIND) create cluster --name $(KIND_CLUSTER)

# test-e2e: unified suite — creates a Kind cluster, deploys the operator, and runs all tests.
#
# Test tiers (controlled by env vars):
#   default             operator + webhook tests (manager)
#   STREAMING_E2E=true  + SSE token streaming tests (needs LLM credentials)
#
# Examples:
#   make test-e2e
#   STREAMING_E2E=true make test-e2e
.PHONY: test-e2e
test-e2e: setup-test-e2e manifests generate fmt vet ## Run the e2e suite
	KIND=$(KIND) KIND_CLUSTER=$(KIND_CLUSTER) ROUTER_IMG=$(ROUTER_IMG) STREAMING_E2E=$(STREAMING_E2E) go test -tags=e2e ./test/e2e/ -v -ginkgo.v
	$(MAKE) cleanup-test-e2e

.PHONY: lint-demos
lint-demos: ## Validate all demo Helm charts render valid Kubernetes YAML.
	@fail=0; \
	for chart in charts/demos/*/; do \
		name=$$(basename "$$chart"); \
		if ! helm template "$$name" "$$chart" --namespace agent-orca-system > /tmp/agent-orca-lint-demo.yaml 2>&1; then \
			echo "FAIL: $$name (helm template error)"; \
			cat /tmp/agent-orca-lint-demo.yaml; \
			fail=1; \
		elif ! kubectl apply --dry-run=client -f /tmp/agent-orca-lint-demo.yaml > /dev/null 2>&1; then \
			echo "FAIL: $$name (kubectl dry-run error)"; \
			kubectl apply --dry-run=client -f /tmp/agent-orca-lint-demo.yaml 2>&1 | grep -i error || true; \
			fail=1; \
		else \
			echo "OK: $$name"; \
		fi; \
	done; \
	rm -f /tmp/agent-orca-lint-demo.yaml; \
	if [ "$$fail" -ne 0 ]; then exit 1; fi

.PHONY: cleanup-test-e2e
cleanup-test-e2e: ## Tear down the Kind cluster used for e2e tests
	@$(KIND) delete cluster --name $(KIND_CLUSTER)

.PHONY: test-ui
test-ui: ## Run UI unit and component tests.
	cd ui && npm test

.PHONY: test-ui-e2e
test-ui-e2e: ## Run UI E2E tests with Playwright.
	cd ui && npx playwright test

.PHONY: lint
lint: golangci-lint ui-proxy-dist ## Run golangci-lint linter
	"$(GOLANGCI_LINT)" run

.PHONY: lint-fix
lint-fix: golangci-lint ## Run golangci-lint linter and perform fixes
	"$(GOLANGCI_LINT)" run --fix

.PHONY: lint-config
lint-config: golangci-lint ## Verify golangci-lint linter configuration
	"$(GOLANGCI_LINT)" config verify

##@ Build

.PHONY: build
build: manifests generate fmt vet ## Build manager binary.
	go build -o bin/manager cmd/main.go

.PHONY: build-model-router
build-model-router: fmt vet ## Build model-router sidecar binary.
	go build -o bin/model-router ./cmd/model-router

.PHONY: build-mcp-ingester
build-mcp-ingester: fmt vet ## Build mcp-ingester binary.
	go build -o bin/mcp-ingester ./cmd/mcp-ingester

.PHONY: build-ui-proxy
build-ui-proxy: ## Build the UIProxy binary (requires npm run build first).
	@echo "Building React SPA..."
	cd ui && npm run build
	@echo "Copying dist to cmd/ui-proxy/dist/..."
	rm -rf cmd/ui-proxy/dist && cp -r ui/dist cmd/ui-proxy/dist
	@echo "Building ui-proxy binary..."
	go build -o bin/ui-proxy ./cmd/ui-proxy

.PHONY: build-causal-ui
build-causal-ui: ## Build the causal discovery UI Docker image locally.
	$(CONTAINER_TOOL) build -t agent-orca/causal-discovery-ui:latest charts/demos/demo-causal-discovery

.PHONY: run
run: manifests generate fmt vet ## Run a controller from your host.
	STATE_BACKEND=redis REDIS_URL=$${REDIS_URL:-redis://localhost:6379} OPERATOR_API_URL=$${OPERATOR_API_URL:-http://localhost:8082} go run ./cmd/main.go

# If you wish to build the manager image targeting other platforms you can use the --platform flag.
# (i.e. docker build --platform linux/arm64). However, you must enable docker buildKit for it.
# More info: https://docs.docker.com/develop/develop-images/build_enhancements/
.PHONY: docker-build
docker-build: ## Build docker image with the manager.
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image with the manager.
	$(CONTAINER_TOOL) push ${IMG}

.PHONY: docker-build-model-router
docker-build-model-router: ## Build docker image for the model-router sidecar.
	$(CONTAINER_TOOL) build -t ${ROUTER_IMG} -f Dockerfile.model-router .

# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry (i.e. if you do not set a valid value via IMG=<myregistry/image:<tag>> then the export will fail)
# To adequately provide solutions that are compatible with multiple platforms, you should consider using this option.
PLATFORMS ?= linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
.PHONY: docker-buildx
docker-buildx: ## Build and push docker image for the manager for cross-platform support
	# copy existing Dockerfile and insert --platform=${BUILDPLATFORM} into Dockerfile.cross, and preserve the original Dockerfile
	sed -e '1 s/\(^FROM\)/FROM --platform=\$$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$$\{BUILDPLATFORM\}/' Dockerfile > Dockerfile.cross
	- $(CONTAINER_TOOL) buildx create --name agent-orca-builder
	$(CONTAINER_TOOL) buildx use agent-orca-builder
	- $(CONTAINER_TOOL) buildx build --push --platform=$(PLATFORMS) --tag ${IMG} -f Dockerfile.cross .
	- $(CONTAINER_TOOL) buildx rm agent-orca-builder
	rm Dockerfile.cross

.PHONY: build-installer
build-installer: manifests generate kustomize ## Generate a consolidated YAML with CRDs and deployment.
	mkdir -p dist
	cd config/manager && "$(KUSTOMIZE)" edit set image controller=${IMG}
	"$(KUSTOMIZE)" build config/default > dist/install.yaml

##@ Deployment

ifndef ignore-not-found
  ignore-not-found = false
endif

.PHONY: install
install: manifests kustomize ## Install CRDs into the K8s cluster specified in ~/.kube/config.
	@out="$$( "$(KUSTOMIZE)" build config/crd 2>/dev/null || true )"; \
	if [ -n "$$out" ]; then echo "$$out" | "$(KUBECTL)" apply --server-side --force-conflicts --field-manager=helm -f -; else echo "No CRDs to install; skipping."; fi

.PHONY: uninstall
uninstall: manifests kustomize ## Uninstall CRDs from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
	@out="$$( "$(KUSTOMIZE)" build config/crd 2>/dev/null || true )"; \
	if [ -n "$$out" ]; then echo "$$out" | "$(KUBECTL)" delete --ignore-not-found=$(ignore-not-found) -f -; else echo "No CRDs to delete; skipping."; fi

.PHONY: deploy
deploy: manifests kustomize ## Deploy controller to the K8s cluster specified in ~/.kube/config.
	cd config/manager && "$(KUSTOMIZE)" edit set image controller=${IMG}
	"$(KUSTOMIZE)" build config/default | "$(KUBECTL)" apply -f -

.PHONY: undeploy
undeploy: kustomize ## Undeploy controller from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
	"$(KUSTOMIZE)" build config/default | "$(KUBECTL)" delete --ignore-not-found=$(ignore-not-found) -f -

##@ Dependencies

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p "$(LOCALBIN)"

## Tool Binaries
KUBECTL ?= kubectl
KIND ?= kind
KUSTOMIZE ?= $(LOCALBIN)/kustomize
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen
ENVTEST ?= $(LOCALBIN)/setup-envtest
GOLANGCI_LINT = $(LOCALBIN)/golangci-lint

## Tool Versions
KUSTOMIZE_VERSION ?= v5.8.1
CONTROLLER_TOOLS_VERSION ?= v0.20.1

#ENVTEST_VERSION is the version of controller-runtime release branch to fetch the envtest setup script (i.e. release-0.20)
ENVTEST_VERSION ?= $(shell v='$(call gomodver,sigs.k8s.io/controller-runtime)'; \
  [ -n "$$v" ] || { echo "Set ENVTEST_VERSION manually (controller-runtime replace has no tag)" >&2; exit 1; }; \
  printf '%s\n' "$$v" | sed -E 's/^v?([0-9]+)\.([0-9]+).*/release-\1.\2/')

#ENVTEST_K8S_VERSION is the version of Kubernetes to use for setting up ENVTEST binaries (i.e. 1.31)
ENVTEST_K8S_VERSION ?= $(shell v='$(call gomodver,k8s.io/api)'; \
  [ -n "$$v" ] || { echo "Set ENVTEST_K8S_VERSION manually (k8s.io/api replace has no tag)" >&2; exit 1; }; \
  printf '%s\n' "$$v" | sed -E 's/^v?[0-9]+\.([0-9]+).*/1.\1/')

GOLANGCI_LINT_VERSION ?= v2.8.0
.PHONY: kustomize
kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary.
$(KUSTOMIZE): $(LOCALBIN)
	$(call go-install-tool,$(KUSTOMIZE),sigs.k8s.io/kustomize/kustomize/v5,$(KUSTOMIZE_VERSION))

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: setup-envtest
setup-envtest: envtest ## Download the binaries required for ENVTEST in the local bin directory.
	@echo "Setting up envtest binaries for Kubernetes version $(ENVTEST_K8S_VERSION)..."
	@"$(ENVTEST)" use $(ENVTEST_K8S_VERSION) --bin-dir "$(LOCALBIN)" -p path >/dev/null || { \
		echo "Error: Failed to set up envtest binaries for version $(ENVTEST_K8S_VERSION)."; \
		exit 1; \
	}

.PHONY: envtest
envtest: $(ENVTEST) ## Download setup-envtest locally if necessary.
$(ENVTEST): $(LOCALBIN)
	$(call go-install-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest,$(ENVTEST_VERSION))

.PHONY: golangci-lint
golangci-lint: $(GOLANGCI_LINT) ## Download golangci-lint locally if necessary.
$(GOLANGCI_LINT): $(LOCALBIN)
	$(call go-install-tool,$(GOLANGCI_LINT),github.com/golangci/golangci-lint/v2/cmd/golangci-lint,$(GOLANGCI_LINT_VERSION))
	@test -f .custom-gcl.yml && { \
		echo "Building custom golangci-lint with plugins..." && \
		$(GOLANGCI_LINT) custom --destination $(LOCALBIN) --name golangci-lint-custom && \
		mv -f $(LOCALBIN)/golangci-lint-custom $(GOLANGCI_LINT); \
	} || true

# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
# $1 - target path with name of binary
# $2 - package url which can be installed
# $3 - specific version of package
define go-install-tool
@[ -f "$(1)-$(3)" ] && [ "$$(readlink -- "$(1)" 2>/dev/null)" = "$(1)-$(3)" ] || { \
set -e; \
package=$(2)@$(3) ;\
echo "Downloading $${package}" ;\
rm -f "$(1)" ;\
GOBIN="$(LOCALBIN)" go install $${package} ;\
mv "$(LOCALBIN)/$$(basename "$(1)")" "$(1)-$(3)" ;\
} ;\
ln -sf "$$(realpath "$(1)-$(3)")" "$(1)"
endef

define gomodver
$(shell go list -m -f '{{if .Replace}}{{.Replace.Version}}{{else}}{{.Version}}{{end}}' $(1) 2>/dev/null)
endef
