/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	agentorcav1alpha1 "github.com/floppyfish14/agent-orca/api/v1alpha1"
)

const (
	// LabelManagedByMCPServer marks Tools generated by the MCPServer controller.
	LabelManagedByMCPServer = "mcpserver"
	// LabelManagedBy identifies who manages a resource.
	LabelManagedBy = "agentorca.io/managed-by"
	// LabelMCPServer identifies which MCPServer owns a Tool.
	LabelMCPServer = "agentorca.io/mcpserver"
)

// MCPServerReconciler reconciles an MCPServer object.
// It generates one child Tool CR per declared tool in the MCPServer spec.
type MCPServerReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=agentorca.agentorca.io,resources=mcpservers,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=agentorca.agentorca.io,resources=mcpservers/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=agentorca.agentorca.io,resources=mcpservers/finalizers,verbs=update

func (r *MCPServerReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	var server agentorcav1alpha1.MCPServer
	if err := r.Get(ctx, req.NamespacedName, &server); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	// Validate the spec.
	if ready, message := r.validate(&server); !ready {
		return ctrl.Result{}, r.patchStatus(ctx, &server, false, 0, message)
	}

	// List existing child Tools owned by this MCPServer.
	var existingTools agentorcav1alpha1.ToolList
	if err := r.List(ctx, &existingTools,
		client.InNamespace(server.Namespace),
		client.MatchingLabels{
			LabelManagedBy: LabelManagedByMCPServer,
			LabelMCPServer: server.Name,
		},
	); err != nil {
		return ctrl.Result{}, fmt.Errorf("listing child Tools: %w", err)
	}

	// Determine whether this server relies on runtime auto-discovery:
	// discoverability enabled (the default) with no tools explicitly declared.
	discoveryMode := isDiscoveryMode(&server)

	// Build a set of desired child Tool CR names for stale detection.
	// In discovery mode a single "connector" Tool CR is named after the MCPServer
	// itself, so agents list it once in spec.tools instead of enumerating tools.
	desiredNames := make(map[string]struct{})
	if discoveryMode {
		desiredNames[server.Name] = struct{}{}
	} else {
		for _, t := range server.Spec.Tools {
			desiredNames[childToolName(server.Name, t.Name)] = struct{}{}
		}
	}

	// Delete stale child Tools that are no longer desired.
	// This also cleans up per-tool CRs when a server switches between explicit
	// declaration and discovery mode (and vice-versa).
	for i := range existingTools.Items {
		tool := &existingTools.Items[i]
		if _, ok := desiredNames[tool.Name]; !ok {
			if err := r.Delete(ctx, tool); err != nil {
				return ctrl.Result{}, fmt.Errorf("deleting stale Tool %q: %w", tool.Name, err)
			}
		}
	}

	// Build a lookup of existing tools by name for update detection.
	existingByName := make(map[string]*agentorcav1alpha1.Tool, len(existingTools.Items))
	for i := range existingTools.Items {
		existingByName[existingTools.Items[i].Name] = &existingTools.Items[i]
	}

	// Create or update the desired child Tool(s).
	if discoveryMode {
		desired := r.buildMarkerTool(&server)
		if err := r.applyChildTool(ctx, existingByName, &server, desired); err != nil {
			return ctrl.Result{}, fmt.Errorf("reconciling connector Tool %q: %w", desired.Name, err)
		}
	} else {
		for _, declared := range server.Spec.Tools {
			desired := r.buildChildTool(&server, declared)
			if err := r.applyChildTool(ctx, existingByName, &server, desired); err != nil {
				return ctrl.Result{}, fmt.Errorf("reconciling Tool %q: %w", desired.Name, err)
			}
		}
	}

	message := fmt.Sprintf("%d tool(s) reconciled", len(desiredNames))
	if discoveryMode {
		message = "auto-discovery enabled; connector Tool created, all tools discovered at runtime"
	}
	return ctrl.Result{}, r.patchStatus(ctx, &server, true, len(desiredNames), message)
}

// validate checks the MCPServer spec for correctness.
func (r *MCPServerReconciler) validate(server *agentorcav1alpha1.MCPServer) (bool, string) {
	switch server.Spec.Transport {
	case "http", "sse": //nolint:goconst

		if server.Spec.URL == "" {
			return false, fmt.Sprintf("spec.url is required for transport=%s", server.Spec.Transport)
		}
	case "stdio", "":
		if server.Spec.OCIRef == "" {
			return false, "spec.ociRef is required for transport=stdio"
		}
	default:
		return false, fmt.Sprintf("unknown transport %q", server.Spec.Transport)
	}

	// In discovery mode (discoverability enabled, no tools declared) there are no
	// tools to validate — the model-router discovers them all at runtime. Otherwise
	// (explicit declaration, or discoverability disabled) the operator must declare
	// at least one tool so there is a catalog and a referenceable connector.
	if !isDiscoveryMode(server) {
		if len(server.Spec.Tools) == 0 {
			return false, "spec.tools must declare at least one tool (or set spec.discoverability: enabled to auto-discover all tools)"
		}
		seen := make(map[string]struct{}, len(server.Spec.Tools))
		for _, t := range server.Spec.Tools {
			if t.Name == "" {
				return false, "tool name must not be empty"
			}
			if _, dup := seen[t.Name]; dup {
				return false, fmt.Sprintf("duplicate tool name %q", t.Name)
			}
			seen[t.Name] = struct{}{}
		}
	}

	return true, ""
}

// discoverabilityMode returns the effective discoverability value, treating the
// empty/unset value as the documented default ("enabled").
func discoverabilityMode(server *agentorcav1alpha1.MCPServer) string {
	if server.Spec.Discoverability == agentorcav1alpha1.MCPServerDiscoverabilityDisabled {
		return agentorcav1alpha1.MCPServerDiscoverabilityDisabled
	}
	return agentorcav1alpha1.MCPServerDiscoverabilityEnabled
}

// isDiscoveryMode reports whether the MCPServer relies on runtime auto-discovery:
// discoverability is enabled (the default) and no tools are explicitly declared.
func isDiscoveryMode(server *agentorcav1alpha1.MCPServer) bool {
	return discoverabilityMode(server) == agentorcav1alpha1.MCPServerDiscoverabilityEnabled &&
		len(server.Spec.Tools) == 0
}

// buildChildTool constructs the desired Tool CR for a declared MCPServer tool.
func (r *MCPServerReconciler) buildChildTool(server *agentorcav1alpha1.MCPServer, declared agentorcav1alpha1.MCPServerTool) *agentorcav1alpha1.Tool {
	tool := &agentorcav1alpha1.Tool{
		ObjectMeta: metav1.ObjectMeta{
			Name:      childToolName(server.Name, declared.Name),
			Namespace: server.Namespace,
			Labels: map[string]string{
				LabelManagedBy: LabelManagedByMCPServer,
				LabelMCPServer: server.Name,
			},
		},
		Spec: agentorcav1alpha1.ToolSpec{
			Type: agentorcav1alpha1.ToolTypeMCP,
			MCPConfig: &agentorcav1alpha1.MCPConfig{
				Transport: server.Spec.Transport,
				URL:       server.Spec.URL,
				Args:      server.Spec.Args,
				Env:       server.Spec.Env,
				EnvFrom:   server.Spec.EnvFrom,
			},
			OCIRef:        server.Spec.OCIRef,
			ExecutionMode: executionModeForServer(server),
			NetworkEgress: server.Spec.NetworkEgress,
			Resources:     server.Spec.Resources,
			Schema: &agentorcav1alpha1.ToolSchema{
				Description: declared.Description,
				Input:       declared.InputSchema,
			},
		},
	}
	return tool
}

// buildMarkerTool constructs the connector Tool CR created when an MCPServer is in
// auto-discovery mode (discoverability enabled with no tools explicitly declared).
//
// The marker exists so that:
//   - agents can reference the MCPServer by a single name in spec.tools, and
//   - podbuilder can mount the stdio sidecar image volume and rewrite binary paths
//     against a real Tool CR (those mounts are keyed on Tool CR names).
//
// The model-router ignores this Tool's (empty) schema — it discovers every tool at
// runtime via tools/list and exposes them (filtered by includePatterns/excludePatterns).
func (r *MCPServerReconciler) buildMarkerTool(server *agentorcav1alpha1.MCPServer) *agentorcav1alpha1.Tool {
	tool := &agentorcav1alpha1.Tool{
		ObjectMeta: metav1.ObjectMeta{
			Name:      server.Name,
			Namespace: server.Namespace,
			Labels: map[string]string{
				LabelManagedBy: LabelManagedByMCPServer,
				LabelMCPServer: server.Name,
			},
		},
		Spec: agentorcav1alpha1.ToolSpec{
			Type: agentorcav1alpha1.ToolTypeMCP,
			MCPConfig: &agentorcav1alpha1.MCPConfig{
				Transport: server.Spec.Transport,
				URL:       server.Spec.URL,
				Args:      server.Spec.Args,
				Env:       server.Spec.Env,
				EnvFrom:   server.Spec.EnvFrom,
			},
			OCIRef:        server.Spec.OCIRef,
			ExecutionMode: executionModeForServer(server),
			NetworkEgress: server.Spec.NetworkEgress,
			Resources:     server.Spec.Resources,
		},
	}
	return tool
}

// applyChildTool creates or updates a child Tool CR described by desired.
func (r *MCPServerReconciler) applyChildTool(
	ctx context.Context,
	existingByName map[string]*agentorcav1alpha1.Tool,
	server *agentorcav1alpha1.MCPServer,
	desired *agentorcav1alpha1.Tool,
) error {
	if existing, ok := existingByName[desired.Name]; ok {
		// Update if spec changed.
		existing.Spec = desired.Spec
		existing.Labels = desired.Labels
		return r.Update(ctx, existing)
	}
	// Create new child Tool.
	if err := ctrl.SetControllerReference(server, desired, r.Scheme); err != nil {
		return err
	}
	return r.Create(ctx, desired)
}

// executionModeForServer returns "sidecar" when the MCPServer has an OCI image
// and uses stdio transport, meaning the model-router needs the binary mounted
// via an image volume. Otherwise returns empty (default pod execution).
func executionModeForServer(server *agentorcav1alpha1.MCPServer) agentorcav1alpha1.ToolExecutionMode {
	if server.Spec.OCIRef != "" && server.Spec.Transport == "stdio" {
		return agentorcav1alpha1.ToolExecSidecar
	}
	return ""
}

// patchStatus updates the MCPServer status fields and Ready condition.
func (r *MCPServerReconciler) patchStatus(ctx context.Context, server *agentorcav1alpha1.MCPServer, ready bool, toolCount int, message string) error {
	patch := client.MergeFrom(server.DeepCopy())
	server.Status.Ready = ready
	server.Status.Message = message
	server.Status.ToolCount = toolCount
	server.Status.Discovering = isDiscoveryMode(server)

	condStatus := metav1.ConditionTrue
	reason := "Reconciled"
	if !ready {
		condStatus = metav1.ConditionFalse
		reason = "ValidationFailed"
	}
	setCondition(&server.Status.Conditions, metav1.Condition{
		Type:               "Ready",
		Status:             condStatus,
		Reason:             reason,
		Message:            message,
		LastTransitionTime: metav1.Now(),
	})

	return r.Status().Patch(ctx, server, patch)
}

// childToolName returns the DNS-safe name for a child Tool CR.
func childToolName(serverName, toolName string) string {
	name := serverName + "-" + toolName
	// Sanitize to DNS subdomain: lowercase, alphanumeric and hyphens only.
	name = strings.ToLower(name)
	name = dnsUnsafe.ReplaceAllString(name, "-")
	// Truncate to 253 chars (Kubernetes name limit).
	if len(name) > 253 {
		name = name[:253]
	}
	return strings.Trim(name, "-")
}

var dnsUnsafe = regexp.MustCompile(`[^a-z0-9-]`)

// SetupWithManager sets up the controller with the Manager.
func (r *MCPServerReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&agentorcav1alpha1.MCPServer{}).
		Owns(&agentorcav1alpha1.Tool{}).
		Named("mcpserver").
		Complete(r)
}
