# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/agentorca.agentorca.io_modelproviders.yaml
- bases/agentorca.agentorca.io_modelselectors.yaml
- bases/agentorca.agentorca.io_tools.yaml
- bases/agentorca.agentorca.io_agents.yaml
- bases/agentorca.agentorca.io_agentruns.yaml
- bases/agentorca.agentorca.io_agentdeployments.yaml
- bases/agentorca.agentorca.io_agentworkflows.yaml
- bases/agentorca.agentorca.io_mcpservers.yaml
- bases/agentorca.agentorca.io_knowledgebases.yaml
- bases/agentorca.agentorca.io_tenantconfigs.yaml
- bases/agentorca.agentorca.io_guardrailpolicies.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
