{{- $ctx := dict "Values" (index .Values "agent-orca-resources") "Release" .Release "Chart" .Chart "Files" .Files "Template" .Template "Capabilities" .Capabilities }}
{{ include "agent-orca-resources.agents" $ctx }}
{{ include "agent-orca-resources.agentdeployments" $ctx }}
{{ include "agent-orca-resources.tools" $ctx }}
{{ include "agent-orca-resources.mcpservers" $ctx }}
{{ include "agent-orca-resources.mcpserverdeployments" $ctx }}
{{ include "agent-orca-resources.knowledgebases" $ctx }}
